volumes:
  db-trototvn:

services:
  db-trototvn:
    build:
      context: ./infras/docker/mssql
    image: db-trototvn-fts:latest
    container_name: db-trototvn
    hostname: db-trototvn
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${Sa_Password:-00hihiHIHI-}
      - MSSQL_PID=Developer
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - 1433:1433
    volumes:
      - db-trototvn:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    restart: always
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${Sa_Password:-00hihiHIHI-}" -Q "SELECT 1" -C -t 30 || exit 1
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 10s

  sqlserver.configurator:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver.configurator
    volumes:
      - ./infras/db:/scripts
    depends_on:
      db-trototvn:
        condition: service_healthy
    entrypoint: >
      bash -c " echo 'Waiting for SQL Server to be fully ready...'; sleep 15; echo 'Running initialization scripts...'; chmod +x /scripts/run-scripts.sh; /scripts/run-scripts.sh \"${Sa_Password:-00hihiHIHI-}\"; "

  redis-trototvn:
    image: redis:7.0-alpine
    container_name: redis-trototvn
    hostname: redis-trototvn
    ports:
      - 5555:6379
    restart: always

  redis-insight-trototvn:
    image: redis/redisinsight:2.68
    container_name: redis-insight-trototvn
    hostname: redis-insight-trototvn
    ports:
      - 5540:5540
    restart: always
    depends_on:
      - redis-trototvn
    environment:
      - RI_REDIS_PORT=6379
      - RI_REDIS_HOST=redis-trototvn
