debezium.sink.type=redis
debezium.sink.redis.address=redis-trototvn:6379
debezium.sink.redis.message.format=extended

debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector

# Use Redis for offset storage
debezium.source.offset.storage=io.debezium.storage.redis.offset.RedisOffsetBackingStore
debezium.source.offset.storage.redis.address=redis-trototvn:6379
debezium.source.offset.storage.redis.key=offset:dbz.trotot
debezium.source.offset.flush.interval.ms=60000

# PostgreSQL connection
debezium.source.database.hostname=db-trototvn
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=${POSTGRES_PASSWORD}
debezium.source.database.dbname=trotot_db
debezium.source.database.server.name=dbserver
debezium.source.plugin.name=pgoutput

# Topic/Stream naming  
debezium.source.topic.prefix=dbserver
debezium.source.table.include.list=public.posts

# Snapshot mode
debezium.source.snapshot.mode=initial

# Logging
quarkus.log.console.level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] %s%e%n
